/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author User
 */
public class CLAVE extends javax.swing.JFrame {

    /**
     * Creates new form CLAVE
     */
    private String txt;
    public CLAVE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn512 = new javax.swing.JButton();
        btn1024 = new javax.swing.JButton();
        K2048 = new javax.swing.JButton();
        btn2049 = new javax.swing.JButton();
        K3072 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CLAVE");
        setForeground(new java.awt.Color(153, 255, 204));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(151, 150, 22));
        jLabel1.setText("SELECCIONE EL TAMAÑO DE LA");

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(151, 150, 22));
        jLabel2.setText("CLAVE PARA CIFRAR");

        btn512.setBackground(new java.awt.Color(0, 102, 102));
        btn512.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        btn512.setForeground(new java.awt.Color(255, 255, 255));
        btn512.setText("512");
        btn512.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn512ActionPerformed(evt);
            }
        });

        btn1024.setBackground(new java.awt.Color(0, 102, 102));
        btn1024.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        btn1024.setForeground(new java.awt.Color(255, 255, 255));
        btn1024.setText("1024");
        btn1024.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1024ActionPerformed(evt);
            }
        });

        K2048.setBackground(new java.awt.Color(0, 102, 102));
        K2048.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        K2048.setForeground(new java.awt.Color(255, 255, 255));
        K2048.setText("2048");
        K2048.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K2048ActionPerformed(evt);
            }
        });

        btn2049.setBackground(new java.awt.Color(0, 102, 102));
        btn2049.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        btn2049.setForeground(new java.awt.Color(255, 255, 255));
        btn2049.setText("4096");
        btn2049.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2049ActionPerformed(evt);
            }
        });

        K3072.setBackground(new java.awt.Color(0, 102, 102));
        K3072.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        K3072.setForeground(new java.awt.Color(255, 255, 255));
        K3072.setText("3072");
        K3072.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K3072ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn512)
                                .addGap(26, 26, 26)
                                .addComponent(btn1024)
                                .addGap(28, 28, 28)
                                .addComponent(K2048)
                                .addGap(26, 26, 26)
                                .addComponent(K3072)))
                        .addGap(31, 31, 31)
                        .addComponent(btn2049)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn512)
                    .addComponent(btn1024)
                    .addComponent(btn2049)
                    .addComponent(K2048)
                    .addComponent(K3072))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTexto(String txt){
        this.txt = txt;
    }
    private void btn512ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn512ActionPerformed
        resultado res = new resultado();
        res.setLLave(512, txt);
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn512ActionPerformed

    private void btn1024ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1024ActionPerformed
        resultado res = new resultado();
        res.setLLave(1024, txt);
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn1024ActionPerformed

    private void K2048ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K2048ActionPerformed
        resultado res = new resultado();
        res.setLLave(2048, txt);
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_K2048ActionPerformed

    private void btn2049ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2049ActionPerformed
        resultado res = new resultado();
        res.setLLave(4096, txt);
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn2049ActionPerformed

    private void K3072ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K3072ActionPerformed
        resultado res = new resultado();
        res.setLLave(3072, txt);
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_K3072ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton K2048;
    private javax.swing.JButton K3072;
    private javax.swing.JButton btn1024;
    private javax.swing.JButton btn2049;
    private javax.swing.JButton btn512;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
